# gradle
org.gradle.warning.mode=all
org.gradle.java.installations.auto-download=false
org.gradle.welcome=never
org.gradle.jvmargs=-Xms1G -Xmx1G
org.gradle.jvm.environment=jreRuntimeElements
# https://docs.gradle.org/current/userguide/configuration_cache_enabling.html
org.gradle.configuration-cache=true
org.gradle.tooling.parallel=true
org.gradle.workers.max=1
org.gradle.vfs.watch=true
# kotlin
kotlin.code.style=official
kotlin.jvm.target.validation.mode=ERROR
kotlin.daemon.jvmargs=-Xms1G -Xmx1G
